import "server-only"

import { createHash } from "node:crypto"
import { readStorageConfiguration, type StorageAdapter } from "../storage/index"
import type { StorageObjectMetadata } from "../storage/types"

/**
 * Trusted server-generated-object path (approved design): completed PDFs are
 * produced by the server from a pristine, previously validated template plus
 * database field values. They do NOT transit quarantine or GuardDuty — their
 * StoredObject is honestly recorded NOT_SCANNED (generated internally), and
 * must never be represented as CLEAN.
 */
export class GeneratedPdfStorageError extends Error {
  constructor(message: string) {
    super(message)
    this.name = "GeneratedPdfStorageError"
  }
}

/**
 * S3-configured staging/production environments MUST store generated PDFs
 * durably — a failed durable write may never silently downgrade to
 * local-only generation. Development/test without S3 keeps the current
 * local-compatibility behavior.
 */
export function isDurableGenerationRequired(): boolean {
  return readStorageConfiguration().provider === "s3"
}

export interface DurableGeneratedPdf {
  bucket: string
  objectKey: string
  objectVersionId: string
  etag: string | undefined
  checksumSha256: string
  sizeBytes: number
  encryptionKeyRef: string
}

/**
 * Writes generated bytes to the durable bucket with SSE-KMS and no-overwrite
 * preconditions, then verifies checksum, size, MIME type, exact object
 * version, and KMS key against locally computed values. Throws without any
 * database side effect on mismatch; a thrown error after the provider write
 * leaves at most an unowned durable artifact, which reconciliation reports.
 */
export async function storeGeneratedPdfDurably(
  adapter: StorageAdapter,
  key: string,
  bytes: Buffer,
): Promise<DurableGeneratedPdf> {
  const configuration = readStorageConfiguration()
  if (configuration.provider !== "s3") {
    throw new GeneratedPdfStorageError("Durable generated-PDF storage requires the S3 storage configuration.")
  }
  const checksumSha256 = createHash("sha256").update(bytes).digest("hex")
  let written: StorageObjectMetadata
  try {
    written = await adapter.putObject({
      key,
      location: "durable",
      body: bytes,
      expectedContentLength: bytes.length,
      mimeType: "application/pdf",
      checksumSha256,
      encryption: { mode: "sse-kms" },
      preconditions: { ifNoneMatch: true },
      metadata: { generated: "true" },
    })
  } catch {
    throw new GeneratedPdfStorageError("The durable write for the generated document failed.")
  }
  if (
    written.provider !== "s3" ||
    !written.versionId ||
    written.checksumSha256 !== checksumSha256 ||
    written.size !== bytes.length ||
    written.mimeType !== "application/pdf" ||
    written.encryptionKeyReference !== configuration.kmsKeyArn
  ) {
    throw new GeneratedPdfStorageError("Durable verification of the generated document failed.")
  }
  return {
    bucket: written.bucket,
    objectKey: written.key,
    objectVersionId: written.versionId,
    etag: written.etag,
    checksumSha256,
    sizeBytes: bytes.length,
    encryptionKeyRef: written.encryptionKeyReference as string,
  }
}
